Repository centfinance/Symmetric.PoolsUI, pull requests merged in 2021-12, with the labels that each got.

#90 Feature/dark light
  src/components/Form/Crp.vue
  src/components/Modal/About.vue
  src/components/Modal/HelpBalance.vue
  src/style.scss
  src/vars.scss
  src/views/Create.vue
  src/views/Home.vue
  src/views/Wallet.vue
Labels: UI-Changes

#96 Feature/dark light
  src/components/Chart.vue
  src/components/Modal/RemoveLiquidity.vue
  src/components/Tabs.vue
Labels: bug

#95 Re-add missing MIVA farm styling
  src/components/List/Pools.vue
  src/views/Pool.vue
Labels: bug

#124 change to reward column title and fixed column hiding bug
  src/components/Container.vue
  src/components/Filters.vue
  src/components/List/Pool.vue
  src/components/List/Pools.vue
  src/components/Page.vue
  src/components/Sidebar.vue
  src/components/Topnav.vue
  src/helpers/utils.ts
  src/locales/de-DE.json
  src/locales/en-US.json
  src/locales/es-ES.json
  src/locales/fr-FR.json
  src/locales/ko-KR.json
  src/locales/pt-BR.json
  src/locales/zh-CN.json
  src/store/modules/subgraph.ts
  src/style.scss
Labels: bug

#133 Update STAKE rewards with GNO rewards
  src/components/List/Pool.vue
  src/components/List/Pools.vue
  src/components/PoolBoxes.vue
  src/helpers/queries.json
  src/helpers/utils.ts
  src/store/modules/subgraph.ts
Labels: WIP

#135 Change to only include Celo reward checks in the Celo build
  src/components/List/Pools.vue
Labels: bug

#138 corrected pool that GNO rewards applied to and fixed SYMM rewards bon…
  src/helpers/miningFactors.ts
  src/helpers/utils.ts
Labels: bug

#139 corrected typo for pools
  src/components/List/Pools.vue
Labels: bug
