Repository centfinance/Symmetric.PoolsUI, pull requests merged in 2021-07, with the labels that each got.

#9 Message added, gas limit set
  package-lock.json
  src/components/PoolHeader.vue
  src/components/Topnav.vue
  src/helpers/web3.ts
Labels: bug

#11 Help section added for wrong network & token bridge
  src/components/Modal/HelpBalance.vue
  src/components/Modal/HelpConnect.vue
  src/components/Topnav.vue
  src/components/Ui/Modal.vue
  src/style.scss
  src/views/Wallet.vue
Labels: enhancement

#12 Some refactoring and changes for full Celo, Alfajores and Sokol support
  package-lock.json
  src/components/Modal/Wrapper.vue
  src/components/PoolHeader.vue
  src/config/alfajores.json
  src/config/celo.json
  src/config/index.ts
  src/config/sokol.json
  src/mixins.ts
  src/store/modules/broadcast.ts
  src/store/modules/web3.ts
  src/views/Create.vue
  src/views/Wallet.vue
  yarn.lock
Labels: enhancement

#13 Split out Sokol build from xDai
  src/_balancer/utils.ts
  src/components/Modal/Wrapper.vue
  src/config/alfajores.json
  src/config/sokol.json
  src/store/modules/broadcast.ts
  src/store/modules/web3.ts
  src/views/Create.vue
  src/views/Wallet.vue
Labels: bug, enhancement

#15 Network Name moved to sidebar
  src/components/Sidebar.vue
  src/components/Topnav.vue
  src/style.scss
  src/vars.scss
Labels: UI-Changes

#19 Minor fixes including adding link to GitBook docs, default icons fix,…
  src/components/Sidebar.vue
  src/components/Token.vue
  src/components/Topnav.vue
  src/config/sokol.json
Labels: bug

#24 Table column changes, show APY, show full values
  package-lock.json
  src/components/List/Pool.vue
  src/components/List/Pools.vue
  src/components/PoolBoxes.vue
  src/helpers/utils.ts
  src/locales/en-US.json
Labels: enhancement
